#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Creates individual and combined audio highlight reels based on timestamp 
information generated by analyze_transcripts.py.

Input: 
- Original audio folder (containing .m4a, .wav, .mp3, etc.)
- Analysis folder (containing _timestamps.json files)

Output:
- Reel folder containing individual highlight reels (e.g., audio_clip_1_reel.mp3).
- Optional combined highlight reel file (e.g., combined_highlights.mp3).

Requires: pydub, FFmpeg (for pydub)
Install pydub: pip install pydub
Ensure FFmpeg is installed and accessible in your system PATH.
"""

import os
import sys
import argparse
import json
import logging
from pathlib import Path
from pydub import AudioSegment
from typing import List, Tuple, Optional
from dotenv import load_dotenv

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Supported audio extensions (align with transcribe_folder.py if necessary)
# Ensure pydub/ffmpeg supports these formats on your system
SUPPORTED_AUDIO_EXTENSIONS = ['.m4a', '.mp3', '.wav', '.ogg', '.flac', '.aac'] 

# --- Audio Processing (Adapted from highlight_creator.py) --- 

def create_highlight_reel(
    base_audio_path: str, 
    timestamps: List[Tuple[float, float]], 
    output_reel_path: str, 
    output_format: str = "mp3",
    silence_padding_ms: int = 500
) -> bool:
    """Slices audio based on timestamps and combines into a single reel file.
    
    Args:
        base_audio_path: Path to the original audio file corresponding to the timestamps.
        timestamps: List of (start_ms, end_ms) tuples for highlights.
        output_reel_path: Path to save the final highlight reel.
        output_format: Desired output format (e.g., "mp3", "wav").
        silence_padding_ms: Milliseconds of silence to add between clips.

    Returns:
        True if the reel was created successfully (even if empty), False otherwise.
    """
    try:
        logger.debug(f"Loading base audio file: {base_audio_path}")
        # Explicitly state format if pydub might struggle with detection (e.g., for m4a)
        file_extension = Path(base_audio_path).suffix.lower().strip('.')
        if file_extension in ['m4a', 'aac']:
            base_audio = AudioSegment.from_file(base_audio_path, format=file_extension)
        else:
            # Let pydub attempt auto-detection for common formats like wav/mp3
            base_audio = AudioSegment.from_file(base_audio_path)
        logger.debug(f"Base audio duration: {len(base_audio) / 1000:.2f} seconds.")
    except FileNotFoundError:
        logger.error(f"Base audio file not found: {base_audio_path}")
        return False
    except Exception as e:
        # Catch specific pydub/ffmpeg errors if possible
        if "ffmpeg".lower() in str(e).lower():
             logger.error(f"Failed to load audio file {base_audio_path}. Ensure FFmpeg is installed and in PATH. Error: {e}")
        else:
             logger.error(f"Failed to load audio file {base_audio_path}: {e}")
        return False

    highlight_reel = AudioSegment.empty()
    padding = AudioSegment.silent(duration=silence_padding_ms)
    total_clips_added = 0

    logger.info(f"Slicing and combining {len(timestamps)} potential segments for {Path(output_reel_path).name}...")
    for i, (start_ms, end_ms) in enumerate(timestamps):
        # Ensure times are valid and within bounds
        start_ms = max(0, float(start_ms))
        end_ms = min(len(base_audio), float(end_ms))
        
        if start_ms >= end_ms:
             logger.warning(f"Skipping invalid timestamp segment {i+1}: start {start_ms:.2f} >= end {end_ms:.2f}")
             continue
             
        logger.debug(f"Extracting segment {i+1}: {start_ms/1000:.2f}s - {end_ms/1000:.2f}s")
        try:
            clip = base_audio[start_ms:end_ms]
            # Add padding *before* the next clip if this is not the first clip
            if total_clips_added > 0:
                 highlight_reel += padding
            highlight_reel += clip
            total_clips_added += 1
        except OverflowError as e:
             logger.error(f"Error processing segment {i+1} ({start_ms:.2f}-{end_ms:.2f} ms): Timestamp likely out of bounds or corrupted audio? Error: {e}")
             continue # Skip segment if error
        except Exception as e:
            logger.error(f"Error slicing segment {i+1} ({start_ms:.2f}-{end_ms:.2f} ms): {e}")
            continue # Skip segment if error

    if len(highlight_reel) == 0:
        logger.warning(f"Highlight reel for {Path(output_reel_path).name} is empty. No valid segments were extracted or timestamps were empty.")
        # Optionally, don't save empty reels
        # return True # Indicate processing finished, even if reel is empty

    # Export the final reel
    try:
        # Ensure the output directory exists
        Path(output_reel_path).parent.mkdir(parents=True, exist_ok=True)
        
        logger.info(f"Exporting highlight reel to {output_reel_path} (format: {output_format})...")
        highlight_reel.export(output_reel_path, format=output_format)
        logger.info(f"Individual reel exported successfully to {output_reel_path}")
        return True
    except Exception as e:
        logger.error(f"Failed to export highlight reel {output_reel_path}: {e}")
        return False

def combine_reels(reel_files: List[str], combined_output_path: str, output_format: str = "mp3", silence_padding_ms: int = 1000) -> bool:
    """Combines multiple audio files into a single file with padding."""
    if not reel_files:
        logger.warning("No individual reel files provided to combine.")
        return False

    combined_audio = AudioSegment.empty()
    padding = AudioSegment.silent(duration=silence_padding_ms)
    
    logger.info(f"Combining {len(reel_files)} individual reels into {combined_output_path}...")
    
    for i, reel_path in enumerate(reel_files):
        try:
            logger.debug(f"Loading individual reel: {reel_path}")
            reel_segment = AudioSegment.from_file(reel_path)
            
            # Add padding before the next reel (except the first one)
            if i > 0:
                combined_audio += padding
            combined_audio += reel_segment
            
        except FileNotFoundError:
            logger.error(f"Individual reel file not found: {reel_path}. Skipping.")
            continue
        except Exception as e:
            logger.error(f"Error loading or processing individual reel {reel_path}: {e}. Skipping.")
            continue
            
    if len(combined_audio) == 0:
        logger.error("Combined audio is empty. Failed to load or process any individual reels.")
        return False

    # Export the combined reel
    try:
        # Ensure the output directory exists
        Path(combined_output_path).parent.mkdir(parents=True, exist_ok=True)
        
        logger.info(f"Exporting combined reel to {combined_output_path} (format: {output_format})...")
        combined_audio.export(combined_output_path, format=output_format)
        logger.info(f"Combined reel exported successfully to {combined_output_path}")
        return True
    except Exception as e:
        logger.error(f"Failed to export combined reel {combined_output_path}: {e}")
        return False

# --- Main Execution --- 

def main():
    # Load environment variables from .env file
    load_dotenv()

    parser = argparse.ArgumentParser(description="Create individual and combined highlight reels from audio files and timestamp JSONs.")
    
    # Input Folders
    parser.add_argument("--audio-folder", required=True, help="Path to the folder containing original audio files (e.g., .m4a, .wav).")
    parser.add_argument("--analysis-folder", required=True, help="Path to the folder containing _timestamps.json files generated by analyze_transcripts.py.")
    
    # Output Folder/Files
    parser.add_argument("--reel-folder", required=True, help="Path to the folder where individual highlight reels will be saved.")
    parser.add_argument("--combined-reel-file", required=False, help="Optional: Path to save the final combined highlight reel (e.g., combined_highlights.mp3). If not provided, only individual reels are created.")
    
    # Optional Arguments
    parser.add_argument("--output-format", default="mp3", help="Output format for audio reels (e.g., mp3, wav). Default: mp3")
    parser.add_argument("--clip-padding-ms", type=int, default=500, help="Milliseconds of silence between clips within an individual reel (default: 500).")
    parser.add_argument("--reel-padding-ms", type=int, default=1000, help="Milliseconds of silence between individual reels when creating the combined reel (default: 1000).")
    parser.add_argument('--skip-existing', action='store_true', help='Skip creating an individual reel if the output file already exists.')

    args = parser.parse_args()

    # --- Validate Folders and Args ---
    audio_folder = Path(args.audio_folder)
    analysis_folder = Path(args.analysis_folder)
    reel_folder = Path(args.reel_folder)

    if not audio_folder.is_dir():
        logger.error(f"Original audio input folder not found: {audio_folder}")
        sys.exit(1)
    if not analysis_folder.is_dir():
        logger.error(f"Analysis input folder (containing timestamps) not found: {analysis_folder}")
        sys.exit(1)
        
    try:
        reel_folder.mkdir(parents=True, exist_ok=True)
        logger.info(f"Individual reels will be saved to: {reel_folder}")
    except OSError as e:
        logger.error(f"Could not create output reel folder {reel_folder}: {e}")
        sys.exit(1)
        
    output_format = args.output_format.lower().strip('.')

    # --- Find Timestamp Files ---
    timestamp_files = list(analysis_folder.glob('*_timestamps.json'))
    if not timestamp_files:
        logger.warning(f"No timestamp files (*_timestamps.json) found in {analysis_folder}")
        sys.exit(0)
        
    logger.info(f"Found {len(timestamp_files)} timestamp files to process.")

    # --- Process Each Timestamp File --- 
    created_reel_paths = []
    success_count = 0
    failure_count = 0
    skipped_count = 0

    for timestamp_path in timestamp_files:
        # Derive base name (e.g., "my_audio" from "my_audio_timestamps.json")
        base_name = timestamp_path.stem.replace('_timestamps', '')
        output_reel_path = reel_folder / f"{base_name}_reel.{output_format}"
        
        logger.info(f"\n--- Processing timestamps: {timestamp_path.name} ---")

        # Skip if output exists and flag is set
        if args.skip_existing and output_reel_path.exists():
            logger.info(f"Skipping '{timestamp_path.name}' because output reel '{output_reel_path.name}' already exists.")
            # Still add to list for potential combination if needed
            created_reel_paths.append(str(output_reel_path)) 
            skipped_count += 1
            success_count +=1 # Count skip as success for summary, as file exists
            continue

        # Find the corresponding original audio file
        original_audio_path = None
        for ext in SUPPORTED_AUDIO_EXTENSIONS:
            potential_path = audio_folder / f"{base_name}{ext}"
            if potential_path.exists():
                original_audio_path = potential_path
                break
            # Check uppercase extension as well? transcribe_folder does this.
            potential_path_upper = audio_folder / f"{base_name}{ext.upper()}"
            if potential_path_upper.exists():
                 original_audio_path = potential_path_upper
                 break
        
        if not original_audio_path:
            logger.error(f"Could not find matching original audio file for base name '{base_name}' in {audio_folder} with extensions {SUPPORTED_AUDIO_EXTENSIONS}. Skipping reel creation.")
            failure_count += 1
            continue

        logger.info(f"Found corresponding audio file: {original_audio_path.name}")

        # Load timestamps
        try:
            with open(timestamp_path, 'r', encoding='utf-8') as f:
                timestamps_ms = json.load(f)
            if not isinstance(timestamps_ms, list) or not all(isinstance(t, (list, tuple)) and len(t) == 2 for t in timestamps_ms):
                 logger.error(f"Invalid format in timestamp file {timestamp_path.name}. Expected a list of [start_ms, end_ms] pairs. Skipping.")
                 failure_count += 1
                 continue
            if not timestamps_ms:
                 logger.warning(f"Timestamp file {timestamp_path.name} is empty or contains no valid pairs. Skipping reel creation.")
                 # Still count as success? Or failure? Let's count as success but log warning.
                 success_count += 1
                 continue

        except json.JSONDecodeError as e:
            logger.error(f"Error decoding JSON from {timestamp_path.name}: {e}. Skipping.")
            failure_count += 1
            continue
        except Exception as e:
            logger.error(f"Error reading timestamp file {timestamp_path.name}: {e}. Skipping.")
            failure_count += 1
            continue

        # Create the individual reel
        try:
            reel_created = create_highlight_reel(
                str(original_audio_path), # Pass path as string
                timestamps_ms,
                str(output_reel_path),
                output_format=output_format,
                silence_padding_ms=args.clip_padding_ms
            )
            
            if reel_created:
                created_reel_paths.append(str(output_reel_path))
                success_count += 1
            else:
                # Error logged within create_highlight_reel
                failure_count += 1
                
        except Exception as e:
            logger.exception(f"An unexpected error occurred while creating reel for {base_name}: {e}")
            failure_count += 1
            # Continue to the next file

    logger.info("\n--- Individual Reel Creation Summary ---")
    logger.info(f"Successfully created/found: {success_count}")
    logger.info(f"Failed:                   {failure_count}")
    # logger.info(f"Skipped (already exist):  {skipped_count}") # Covered by success count
    logger.info(f"Total processed:          {success_count + failure_count}")
    logger.info("-------------------------------------")

    # --- Combine Reels (Optional) --- 
    if args.combined_reel_file:
        if created_reel_paths: # Only combine if there are reels to combine
             logger.info("\n--- Creating Combined Reel ---")
             combine_success = combine_reels(
                 created_reel_paths,
                 args.combined_reel_file,
                 output_format=output_format,
                 silence_padding_ms=args.reel_padding_ms
             )
             if not combine_success:
                 logger.error("Failed to create the combined highlight reel.")
                 # Exit with error if combining fails? Or just log?
                 # sys.exit(1) 
        else:
            logger.warning("No individual reels were successfully created or found. Cannot create combined reel.")

    if failure_count > 0:
        sys.exit(1) # Exit with error code if any reel creation failed

if __name__ == "__main__":
    main() 